Rename Hover.js to hover.js
We ran into a problem in Jenkins that didn't come up in local testing due to Mac OS's case insensitive filesystem.  We are using webpack.  

I was wondering if this file was meant to be included in this commit: https://github.com/casesandberg/reactcss/commit/f2ed31f467934caa00ea472a1125af39828a6b5a

Here the stack trace we got:

ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./components/hover.js in /jenkins/workspace/build_job/node_modules/reactcss/lib
    at /jenkins/workspace/build_job/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/jenkins/workspace/build_job/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /jenkins/workspace/build_job/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /jenkins/workspace/build_job/node_modules/async/lib/async.js:726:13
    at /jenkins/workspace/build_job/node_modules/async/lib/async.js:52:16
    at done (/jenkins/workspace/build_job/node_modules/async/lib/async.js:241:17)
    at /jenkins/workspace/build_job/node_modules/async/lib/async.js:44:16
    at /jenkins/workspace/build_job/node_modules/async/lib/async.js:723:17
    at /jenkins/workspace/build_job/node_modules/async/lib/async.js:167:37
    at /jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /jenkins/workspace/build_job/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/jenkins/workspace/build_job/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/jenkins/workspace/build_job/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
resolve file
  /jenkins/workspace/build_job/node_modules/reactcss/lib/components/hover.js doesn't exist
  /jenkins/workspace/build_job/node_modules/reactcss/lib/components/hover.js.js doesn't exist
  /jenkins/workspace/build_job/node_modules/reactcss/lib/components/hover.js.jsx doesn't exist
resolve directory
  /jenkins/workspace/build_job/node_modules/reactcss/lib/components/hover.js doesn't exist (directory default file)
  /jenkins/workspace/build_job/node_modules/reactcss/lib/components/hover.js/package.json doesn't exist (directory description file)